env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
settings:
  react:
    version: detect