backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'feat: create {{collection}} “{{slug}}”'
    update: 'feat: update {{collection}} “{{slug}}”'
    delete: 'feat: delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] chore: upload “{{path}}”'
    deleteMedia: '[skip ci] chore: delete “{{path}}”'

# local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'smartLinks'
    label: 'Smart Links'
    folder: 'src/pages/smartLinks'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'smart-link',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Main Image', name: 'mainImage', widget: image }
      - label: 'Links'
        name: 'links'
        widget: 'list'
        summary: '{{fields.linkObject.url}}'
        fields:
          - label: 'Link'
            name: 'linkObject'
            widget: object
            fields:
              - { label: 'Link Image', name: 'linkImage', widget: 'image' }
              - { label: 'URL', name: 'url', widget: 'string' }
